accounts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(    r'login/$', 
            'django.contrib.auth.views.login',
            {'template_name': 'accounts/login.html'},
            name = 'accounts_login'
    ),
    url(    r'logout/$',
            'django.contrib.auth.views.logout',
            {'template_name': 'accounts/logged_out.html'},
            name = 'accounts_logout'
    ),
    url(    r'register/$',
            'accounts.views.register',
            name = 'accounts_register'
    ),
    url(    r'account/$',
            'accounts.views.account_edit',
            name = 'accounts_account_edit'
    ),
    url(    r'password_change/$',
            'accounts.views.password_change',
            name = 'accounts_password_change'
    ),
    
    url(    r'profile/(?P<user_id>\d+)/$',
            'accounts.views.profile',
            name = 'accounts_profile'
    ),
    url(    r'profile/$',
            'accounts.views.my_profile',
            name = 'accounts_my_profile'
    ),
    url(    r'profile/new/$',
            'accounts.views.my_profile_new',
            name = 'accounts_my_profile_new'
    ),
    url(    r'profile/edit/$',
            'accounts.views.my_profile_edit',
            name = 'accounts_my_profile_edit'
    ),
    
    url(    r'profile/realtor/(?P<user_id>\d+)/$',
            'accounts.views.profile_realtor',
            name = 'accounts_profile_realtor'
    ),
    url(    r'profile/realtor/$',
            'accounts.views.my_profile_realtor',
            name = 'accounts_my_profile_realtor'
    ),
    url(    r'profile/realtor/new/$',
            'accounts.views.realtor_new',
            name = 'accounts_my_profile_realtor_new'
    ),
    url(    r'profile/realtor/edit/$',
            'accounts.views.realtor_edit',
            name = 'accounts_my_profile_realtor_edit'
    ),
    
    url(    r'agency/list/$',
            'accounts.views.agency_list',
            name = 'accounts_agency_list'
    ),
    url(    r'agency/(?P<object_id>\d+)/$',
            'accounts.views.agency_detail',
            name = 'accounts_agency_detail'
    ),
    url(    r'agency/new/$',
            'accounts.views.agency_new',
            name = 'accounts_agency_new'
    ),
    url(    r'agency/(?P<object_id>\d+)/edit/$',
            'accounts.views.agency_edit',
            name = 'accounts_agency_edit'
    ),
    url(    r'agency/(?P<object_id>\d+)/delete/$',
            'accounts.views.agency_delete',
            name = 'accounts_agency_delete'
    ),
    
)

urls.py
# -*- coding:utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^realtors/', include('realtors.foo.urls')),
    (r'^$', include('welcome.urls')),
    
    (r'^accounts/', include('accounts.urls')),
    (r'^buildings/', include('buildings.urls')),
    
    (r'^images/', include('images.urls')),
    (r'^messages/', include('usermessages.urls')),
    # Django comments system
    (r'^comments/', include('django.contrib.comments.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

# ¡¡¡ Only in dev mode !!!
if settings.SERVE_STATIC:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )
    
    media_url = settings.MEDIA_URL
    if media_url[0] == '/':
        media_url = media_url[1:]
    urlpatterns += patterns('',
        (r'^%(media_url)s(?P<path>.*)$' % {'media_url': media_url},
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

accounts/models.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from image_utils.modelfields import ResizedImageField

class UserProfile(models.Model):
    GENDER_CHOICES = (
        (True, u'Мужской'),
        (False, u'Женский'),
    )
    
    user = models.ForeignKey(User, unique=True)
    
    birthday = models.DateField(null=True, blank=True, verbose_name=u"День рождения")
    gender = models.NullBooleanField(choices=GENDER_CHOICES, verbose_name=u"Пол")
    
    is_closed = models.BooleanField(default=False, db_index=True, verbose_name=u"Закрыть профиль")
    
    avatar = ResizedImageField(upload_to='avatars', dimensions=settings.AVATAR_SIZE, null=True, blank=True, verbose_name=u"Аватар")
    
    description = models.TextField(null=True, blank=True, verbose_name=u"Дополнительно")
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    deleted_at = models.DateTimeField(null=True, blank=True, editable=False)
    
    def __unicode__(self):
        if self.user.first_name == "" and self.user.last_name == "":
            return "%s's profile" % unicode(self.user)
        return self.get_name
    
    def get_name(self):
        name = " ".join([self.user.first_name, self.user.last_name])
        if name == " ":
            name = str(self.user)
        return name
    
    def get_absolute_url(self):
        return reverse('accounts_profile', args=[self.user.pk])
    
    def can_show(self):
        return not self.is_closed
    

# Managers
class ModeratedAgenciesManager(models.Manager):
    def get_query_set(self):
        return super(ModeratedAgenciesManager, self).get_query_set().filter(is_moderated = True)
    

# Model
class Agency(models.Model):
    administrators = models.ManyToManyField(User, verbose_name=u"Администраторы")
    is_moderated = models.BooleanField(default=False, verbose_name=u"Проверено")
    
    town = models.CharField(max_length = 100, verbose_name=u"Город")
    title = models.CharField(max_length = 150, verbose_name=u"Название")
    address = models.CharField(max_length = 250, null=True, blank=True, verbose_name=u"Адрес")
    phone = models.CharField(max_length = 200, null=True, blank=True, verbose_name=u"Телефон")
    website = models.URLField(max_length = 200, verify_exists=True, null=True, blank=True, verbose_name=u"Сайт")
    email = models.EmailField(max_length = 75, null=True, blank=True, verbose_name=u"e-mail")
    label = ResizedImageField(upload_to='agency_labels', dimensions=settings.AGENCY_LABEL_SIZE, null=True, blank=True, verbose_name=u"Эмблема")
    staff_count = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=u"Кол-во сотрудников")
    establishment_year = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=u"На рынке с", help_text=u"года")
    description = models.TextField(null=True, blank=True, verbose_name=u"Дополнительно")
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    deleted_at = models.DateTimeField(null=True, blank=True, editable=False)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = u"Агентство"
        verbose_name_plural = u"Агентства"
    
    # ============
    # = Managers =
    # ============
    objects = models.Manager() # default manager
    moderated_objects = ModeratedAgenciesManager()
    
    def is_administrator(self, user):
        return user in self.administrators.all()
    
    def can_edit(self, user):
        return self.is_administrator(user)
    
    def get_absolute_url(self):
        return reverse('accounts_agency_detail', args=[self.pk])
    

class Realtor(models.Model):
    EXPERIENCE_CHOICES = (
        (0, u'Нет опыта'),
        (1, u'1 год'),
        (3, u'3 года'),
        (4, u'более 4 лет'),
    )
    
    user = models.ForeignKey(User, unique=True)
    
    experience = models.PositiveSmallIntegerField(choices=EXPERIENCE_CHOICES, null=True, blank=True, verbose_name=u"Опыт работы")
    is_private = models.BooleanField(default=False, verbose_name=u"Частный риэлтор")
    agencies = models.ManyToManyField(Agency, verbose_name=u"Агентство")
    
    in_sales = models.BooleanField(default=False, verbose_name=u"Продажа")
    in_rents = models.BooleanField(default=False, verbose_name=u"Аренда")
    in_camps = models.BooleanField(default=False, verbose_name=u"Загородная недвижимость")
    in_commercials = models.BooleanField(default=False, verbose_name=u"Коммерческая недвижимость")
    
    in_msk = models.BooleanField(default=True, db_index=True, verbose_name=u"Москва")
    in_msk_region = models.BooleanField(default=False, db_index=True, verbose_name=u"Область")
    
    commission_from = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name=u"Комиссия от")
    commission_to = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name=u"Комиссия до")
    
    deal_commission = models.BooleanField(default=False, verbose_name=u"Договорная комиссия")
    
    phone = models.CharField(max_length = 50, null=True, blank=True, verbose_name=u"Телефон")
    
    rating = models.PositiveSmallIntegerField(default=0, editable=False, verbose_name=u"Рейтинг")
    views_count = models.PositiveIntegerField(default=0, editable=False, verbose_name=u"Кол-во просмотров")
    
    description = models.TextField(null=True, blank=True, verbose_name=u"Дополнительно")
    
    def get_absolute_url(self):
        return reverse('accounts_profile_realtor', args=[self.user.pk])
    
    def can_show(self):
        return True
    


# ===========
# = Signals =
# ===========
def user_created_handler(sender, instance, created, **kwargs):
    if created:
        instance.userprofile_set.create()

post_save.connect(user_created_handler, sender=User, dispatch_uid="users-profilecreation-signal")

accounts/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from accounts.models import UserProfile, Realtor, Agency

class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=30, label=u"Имя пользователя")
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(render_value=False), label=u"Пароль")
    password_retype = forms.CharField(max_length=30, widget=forms.PasswordInput(render_value=False), label=u"Пароль еще раз")
    
    email = forms.EmailField(max_length=75, label=u"Электронная почта")
    
    first_name = forms.CharField(max_length=30, required=False, label=u"Имя")
    last_name = forms.CharField(max_length=30, required=False, label=u"Фамилия")
    
    # =========================
    # = Form-wide validations =
    # =========================
    def clean_password_retype(self):
        password = self.cleaned_data['password']
        password_retype = self.cleaned_data['password_retype']
        if password_retype != password:
            raise forms.ValidationError(u"Пароли не совпадают")
        return password_retype
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username):
            raise forms.ValidationError(u"Это имя уже занято")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(u"Такой email уже зарегистрирован")
        return email
    

class AccountForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)
    

class PasswordChangeForm(forms.Form):
    def __init__(self, *args, **kwargs):
        if 'user' not in kwargs:
            raise TypeError('PasswordChangeForm "user" parameter is mandatory')
        self.user = kwargs.pop('user')
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
    
    old_password = forms.CharField(max_length=30, widget=forms.PasswordInput(render_value=False), label=u"Текущий пароль")
    password = forms.CharField(max_length=30, widget=forms.PasswordInput(render_value=False), label=u"Новый пароль")
    password_retype = forms.CharField(max_length=30, widget=forms.PasswordInput(render_value=False), label=u"Новый пароль еще раз")
    
    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if not self.user.check_password(old_password):
            raise forms.ValidationError(u"Неверный пароль")
        return old_password
    
    def clean_password_retype(self):
        password = self.cleaned_data['password']
        password_retype = self.cleaned_data['password_retype']
        if password_retype != password:
            raise forms.ValidationError(u"Пароли не совпадают")
        return password_retype
    


class UserprofileForm(forms.ModelForm):
    class Meta:
        from form_utils.widgets import CalendarWidget
        
        model = UserProfile
        fields = ('birthday', 'gender', 'is_closed', 'avatar', 'description')
        widgets = {
            'birthday': CalendarWidget,
        }
    

class RealtorForm(forms.ModelForm):
    from form_utils.widgets import DivCheckboxSelectMultiple
    
    agencies = forms.ModelMultipleChoiceField(
                                label=u"Агентство",
                                required = False,
                                help_text=u"Если вашего агентства нет в списке, вы можете его <a href=\"/accounts/agency/new\">добавить</a>",
                                queryset=Agency.moderated_objects.all(),
                                widget=DivCheckboxSelectMultiple(classes=['scroll'])
                            )
    
    class Meta:
        model = Realtor
        fields = ('experience', 'agencies', 'is_private', 'in_sales', 'in_rents', 'in_camps', 'in_commercials', 'in_msk', 'in_msk_region', 'commission_from', 'commission_to', 'deal_commission', 'phone', 'description')
    

class AgencyFormBase(forms.ModelForm):
    class Meta:
        model = Agency
    

class AgencyForm(AgencyFormBase):
    class Meta(AgencyFormBase.Meta):
        exclude = ('administrators', 'is_moderated',)

templates/accounts/account_form.html
{% extends "accounts/user_settings_base.html" %}

{% block page %}
	
	<div class="span-18 last">
		<h3>Профиль {% if form.instance.pk %}{{ form.instance.get_profile.get_name }}{% endif %}</h3>
	</div>
	
	<form action="" method="post">
		{% csrf_token %}
		<div class="form span-18 last">
			<div class="non_field_errors span-18 last">
				{{ form.non_field_errors }}
			</div>
			{# {% for field in form %} #}
			{# 	<div class="field span-18 last"> #}
			{# 		<div class="label align-right span-4"> #}
			{# 			{{ field.label_tag }} #}
			{# 		</div> #}
			{# 		<div class="input align-left span-6"> #}
			{# 			{{ field }} #}
			{# 		</div> #}
			{# 		<div class="input_errors align-left span-8 last"> #}
			{# 			{{ field.errors }} #}
			{# 		</div> #}
			{# 	</div> #}
			{# {% endfor %} #}
			
			<div class="field span-18 last">
				<div class="label align-right span-4">
					<label for="id_first_name">Имя</label>
				</div>
				<div class="input align-left span-6">
					{{ form.first_name }}
				</div>
				<div class="input_errors align-left span-8 last">
					{{ form.first_name.errors }}
				</div>
			</div>
			
			<div class="field span-18 last">
				<div class="label align-right span-4">
					<label for="id_last_name">Фамилия</label>
				</div>
				<div class="input align-left span-6">
					{{ form.last_name }}
				</div>
				<div class="input_errors align-left span-8 last">
					{{ form.last_name.errors }}
				</div>
			</div>
			
			<div class="field span-18 last">
				<div class="label align-right span-4">
					<label for="id_email">e-mail</label>
				</div>
				<div class="input align-left span-6">
					{{ form.email }}
				</div>
				<div class="input_errors align-left span-8 last">
					{{ form.email.errors }}
				</div>
			</div>
			
			<div class="field submit span-18 last">
				<input type="submit" class="submit" value="Сохранить" />
			</div>
		</div>
	</form>
{% endblock %}

templates/accounts/agency_base.html
{% extends "base.html" %}

templates/accounts/agency_detail.html
{% extends "accounts/agency_base.html" %}
{% load fields_render %}

{% block sub_header %}
	<h4>{{ object.title }}</h4>
{% endblock %}

{% block top_panel %}
	{% if show_object_controls %}
		<ul class="menu">
			<li><a href="{% url accounts_agency_list %}">&larr; Назад к списку агентств</a></li>
			<li><a href="{% url accounts_agency_edit object.pk %}">Редактировать</a></li>
			<li><a href="{% url accounts_agency_delete object.pk %}">Удалить</a></li>
		</ul>
	{% endif %}
{% endblock %}

{% block content %}
	{% if object.label %}
		<div class="span-24 last">
			<img src="{{ object.label.url }}" />
		</div>
	{% endif %}
	
	{# Left col #}
	<div class="span-12">
		<div class="span-12 last">
			<div class="section_title">Адрес</div>
			<ul>
				{% render_field object.town "Город" %}
				{% render_field object.address "Адрес" %}
			</ul>
		</div>
		<div class="span-12 last">
			<a href="{% url buildings_agency_object_list object.pk %}">Объекты</a>
		</div>
	</div>
	
	{# Right col #}
	<div class="span-12 last">
		<div class="section_title">Контакты</div>
		<ul>
			{% render_field object.phone "Телефон" %}
			{% if object.website %}
				<li>
					Сайт: <span>{{ object.website|urlize }}</span>
				</li>
			{% endif %}
			{% render_field object.email "e-mail" %}
		</ul>
	</div>
	
	{% if object.description %}
		<div class="span-24 last">
			<div class="section_title">Дополнительно</div>
			<div class="description">
				{{ object.description }}
			</div>
		</div>
	{% endif %}
{% endblock %}

templates/accounts/agency_list.html
{% extends "accounts/agency_base.html" %}

{% block content %}
	<div id="management_panel" class="span-24 last">
		<ul class="menu">
			{% if show_management_panel %}
				<li><a href="{% url accounts_agency_new %}">Добавить агентство</a></li>
			{% endif %}
		</ul>
	</div>
	
	<div id="object_list" class="span-24 last">
		{% if object_list %}
			<table>
				<thead>
					<col/>
					<col/>
					<col/>
					<col/>
					<col/>
					<col/>
					
					<tr>
						<th>№</th>
						<th>Город</th>
						<th>Название</th>
						<th>Адрес</th>
						<th>Телефон</th>
						<th>Сайт</th>
					</tr>
				</thead>
				<tbody>
					{% for agency in object_list %}
						<tr>
							<td><a href="{{ agency.get_absolute_url }}">{{ forloop.counter }}</a></td>
							<td>{{ agency.town }}</td>
							<td>{{ agency.title }}</td>
							<td>{{ agency.address }}</td>
							<td>{{ agency.phone }}</td>
							<td>{{ agency.website|urlize }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		{% else %}
			<h3>Ничего не найдено</h3>
		{% endif %}
	</div>
{% endblock %}

templates/accounts/logged_out.html
{% extends "accounts/base.html" %}

{% block content %}
	<h1>Выход из системы выполнен</h1>
{% endblock %}

templates/accounts/login.html
{% extends "accounts/base.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<input type="hidden" name="next" value="{{ next }}" />
		<div class="form span-24 last">
			<div class="non_field_errors span-24 last">
				{{ form.non_field_errors }}
			</div>
			{% for field in form %}
				<div class="field span-24 last">
					<div class="label align-right span-4">
						{{ field.label_tag }}
					</div>
					<div class="input align-left span-6">
						{{ field }}
					</div>
					<div class="input_errors align-left span-14 last">
						{{ field.errors }}
					</div>
				</div>
			{% endfor %}
			<div class="field submit span-24 last">
				<input type="submit" class="submit" value="Войти" />
			</div>
		</div>
	</form>
{% endblock %}

templates/accounts/password_change_form.html
{% extends "accounts/user_settings_base.html" %}

{% block page %}
	<form action="" method="post">
		{% csrf_token %}
		<div class="form span-18 last">
			<div class="non_field_errors span-18 last">
				{{ form.non_field_errors }}
			</div>
			{% for field in form %}
				<div class="field span-18 last">
					<div class="label align-right span-4">
						{{ field.label_tag }}
					</div>
					<div class="input align-left span-6">
						{{ field }}
					</div>
					<div class="input_errors align-left span-8 last">
						{{ field.errors }}
					</div>
				</div>
			{% endfor %}
			<div class="field submit span-18 last">
				<input type="submit" class="submit" value="Изменить" />
			</div>
		</div>
	</form>
{% endblock %}

templates/accounts/realtor.html
{% extends "accounts/realtor_settings_base.html" %}
{% load fields_render %}

{% block sub_header %}
	<h4>Профиль риэлтора {{ realtor.user.get_profile.get_name }}</h4>
{% endblock %}

{% block top_panel %}
	{% if user.pk == realtor.user.pk %}
		<ul class="menu">
			<li>
				<a href="{% url accounts_my_profile_realtor_edit %}">Редактировать</a>
			</li>
		</ul>
	{% endif %}
{% endblock %}

{% block page %}
	<div class="span-9">
		<div class="section_title">Риэлтор</div>
		<ul>
			{% flag_field realtor.is_private "Частный риэлтор" %}
			{% if realtor.agencies.exists %}
				<li>
					Агентство:
					<ul>
						{% for agency in realtor.agencies.all %}
							<li><a href="{{ agency.get_absolute_url }}">{{ agency }}</a></li>
						{% endfor %}
					</ul>
				</li>
			{% endif %}
			{% render_field realtor.get_experience_display "Опыт работы" %}
			{% render_field realtor.phone "Телефон" %}
		</ul>

		<div class="section_title">Виды деятельности</div>
		<ul>
			{% flag_field realtor.in_sales "Продажа" %}
			{% flag_field realtor.in_rents "Аренда" %}
			{% flag_field realtor.in_camps "Загородная недвижимость" %}
			{% flag_field realtor.in_commercials "Коммерческая недвижимость" %}
		</ul>
	</div>
	
	
	<div class="span-9 last">
		<div class="section_title">Регион</div>
		<ul>
			{% flag_field realtor.in_msk "Москва" %}
			{% flag_field realtor.in_msk_region "Область" %}
		</ul>

		<div class="section_title">Комиссия</div>
		<ul>
			{% render_field realtor.commission_from "Комиссия от" %}
			{% render_field realtor.commission_to "Комиссия до" %}
			{% flag_field realtor.deal_commission "Договорная комиссия" %}
		</ul>
	</div>
	
	{% if realtor.description %}
		<div class="span-18 last">
			<div class="section_title">Дополнительно</div>
			<div class="description">
				{{ realtor.description }}
			</div>
		</div>
	{% endif %}
	
{% endblock %}

templates/accounts/realtor_settings_base.html
{% extends "accounts/user_settings_base.html" %}

templates/accounts/user_form.html
{% extends "accounts/base.html" %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<div class="form span-24 last">
			<div class="non_field_errors span-24 last">
				{{ form.non_field_errors }}
			</div>
			{% for field in form %}
				<div class="field span-24 last">
					<div class="label align-right span-4">
						{{ field.label_tag }}
					</div>
					<div class="input align-left span-6">
						{{ field }}
					</div>
					<div class="input_errors align-left span-14 last">
						{{ field.errors }}
					</div>
				</div>
			{% endfor %}
			<div class="field submit span-24 last">
				<input type="submit" class="submit" value="Зарегистрироваться" />
			</div>
		</div>
	</form>
{% endblock %}

templates/accounts/user_settings_base.html
{% extends "accounts/base.html" %}

{% block content %}
	<div class="sidebar span-6">
		{% if user.get_profile and user.get_profile.avatar %}
			<div class="span-6 last">
				<img src="{{ user.get_profile.avatar.url }}" />
			</div>
		{% endif %}
		
		{% if user_id %}
			<div class="span-6 last">
				<ul>
					<li><a href="{% url buildings_user_object_list user_id %}">Объекты этого риэлтора</a></li>
					<li><a href="{% url usermessages_message_new user_id %}">Отправить сообщение</a></li>
				</ul>
			</div>
		{% else %}
			{% if user.is_authenticated %}
				<div class="span-6 last">
					<ul>
						<li><a href="{% url accounts_my_profile %}">Личные данные</a></li>
						<li>
							{% if not user.realtor_set.exists %}
								<a href="{% url accounts_my_profile_realtor_new %}">Обновиться до риэлтора</a>
							{% else %}
								<a href="{% url accounts_my_profile_realtor %}">Профиль риэлтора</a>
							{% endif %}
						</li>
					</ul>
				</div>
				<div class="span-6 last">
					<ul>
						<li><a href="{% url accounts_password_change %}">Изменить пароль</a></li>
					</ul>
				</div>
			{% endif %}
		{% endif %}
	</div>
	
	<div class="page span-18 last">
		{% block page %}{% endblock %}
	</div>
{% endblock %}

templates/accounts/userprofile.html
{% extends "accounts/userprofile_settings_base.html" %}
{% load fields_render %}

{% block sub_header %}
	<h4>Профиль {{ userprofile.get_name }}</h4>
{% endblock %}

{% block page %}
	<div class="span-9">
		<div class="span-9 last">
			<div class="section_title">ФИО</div>
			<ul>
				{% render_field userprofile.user.first_name "Имя" %}
				{% render_field userprofile.user.last_name "Фамилия" %}
				{% render_field userprofile.user.email "email" %}
			</ul>
		</div>
		{% if user.pk == userprofile.user.pk %}
			<div class="span-9 last">
				<ul class="menu">
					<li>
						<a href="{% url accounts_account_edit %}">Редактировать</a>
					</li>
				</ul>
			</div>
		{% endif %}
	</div>
	
	<div class="span-9 last">
		<div class="span-9 last">
			<div class="section_title">Личные данные</div>
			<ul>
				{% render_field userprofile.birthday "День рождения" %}
				{% render_field userprofile.get_gender_display "Пол" %}
			</ul>
		</div>
		{% if user.pk == userprofile.user.pk %}
			<div class="span-9 last">
				<ul class="menu">
					<li>
						<a href="{% url accounts_my_profile_edit %}">Редактировать</a>
					</li>
				</ul>
			</div>
		{% endif %}
	</div>
	
	{# Begin realtor profile #}
		{% if user.pk != userprofile.user.pk and userprofile.user.realtor_set.exists %}
			{% with userprofile.user.realtor_set.get as realtor %}
				<div class="span-9">
					<div class="section_title">Риэлтор</div>
					<ul>
						{% flag_field realtor.is_private "Частный риэлтор" %}
						{% if realtor.agencies.exists %}
							<li>
								Агентство:
								<ul>
									{% for agency in realtor.agencies.all %}
										<li><a href="{{ agency.get_absolute_url }}">{{ agency }}</a></li>
									{% endfor %}
								</ul>
							</li>
						{% endif %}
						{% render_field realtor.get_experience_display "Опыт работы" %}
						{% render_field realtor.phone "Телефон" %}
					</ul>
					
					<div class="section_title">Виды деятельности</div>
					<ul>
						{% flag_field realtor.in_sales "Продажа" %}
						{% flag_field realtor.in_rents "Аренда" %}
						{% flag_field realtor.in_camps "Загородная недвижимость" %}
						{% flag_field realtor.in_commercials "Коммерческая недвижимость" %}
					</ul>
				</div>
				
				
				<div class="span-9 last">
					<div class="section_title">Регион</div>
					<ul>
						{% flag_field realtor.in_msk "Москва" %}
						{% flag_field realtor.in_msk_region "Область" %}
					</ul>
					
					<div class="section_title">Комиссия</div>
					<ul>
						{% render_field realtor.commission_from "Комиссия от" %}
						{% render_field realtor.commission_to "Комиссия до" %}
						{% flag_field realtor.deal_commission "Договорная комиссия" %}
					</ul>
				</div>
			{% endwith %}
		{% endif %}
	{# End realtor profile #}
	
	{% if userprofile.description %}
		<div class="span-18 last">
			<div class="section_title">Дополнительно</div>
			<div class="description">
				{{ userprofile.description }}
			</div>
		</div>
	{% endif %}
	
{% endblock %}

templates/accounts/userprofile_not_found.html
{% extends "accounts/base.html" %}

{% block content %}
	<h3>Профиль не найден</h3>
{% endblock %}

templates/accounts/userprofile_settings_base.html
{% extends "accounts/user_settings_base.html" %}