buildings/urls.py
from django.conf.urls.defaults import *

from buildings.location_dispatcher import LOCATION_FORMS, LocationDispatcher

common_patterns = patterns('buildings.views',
    # (r'/$', 'index'),
    # (r'user/(?P<user_id>\d+)/$', 'user_index'),
)

location_regexp = r"\b%s\b" % r"\b|\b".join([location for location in LOCATION_FORMS])
deal_type_regexp = r"\b%s\b" % r"\b|\b".join([deal_type[0] for deal_type in LocationDispatcher.deal_types()])
object_type_regexp = r"\b%s\b" % r"\b|\b".join([object_type[0] for object_type in LocationDispatcher.object_types()])

object_patterns = patterns('buildings.views',
    url(    r'user/(?P<user_id>\d+)/objects/$',
            'user_object_list',
            name = 'buildings_user_object_list'
    ),
    url(    r'user/(?P<user_id>\d+)/(?P<location>%s)/(?P<object_type>%s)/$' % (location_regexp, object_type_regexp),
            'user_object_list',
            name = 'buildings_user_object_list'
    ),
    url(    r'agency/(?P<agency_id>\d+)/objects/$',
            'agency_object_list',
            name = 'buildings_agency_object_list'
    ),
    url(    r'agency/(?P<agency_id>\d+)/(?P<location>%s)/(?P<object_type>%s)/$' % (location_regexp, object_type_regexp),
            'agency_object_list',
            name = 'buildings_agency_object_list'
    ),
    url(    r'(?P<location>%s)/(?P<object_type>%s)/(?P<id>\d+)/$' % (location_regexp, object_type_regexp),
            'object_detail',
            name = 'buildings_object_detail'
    ),
    url(    r'(?P<location>%s)/(?P<object_type>%s)/new/$' % (location_regexp, object_type_regexp),
            'object_new',
            name = 'buildings_object_new'
    ),
    url(    r'(?P<location>%s)/(?P<object_type>%s)/(?P<id>\d+)/edit/$' % (location_regexp, object_type_regexp),
            'object_edit',
            name = 'buildings_object_edit'
    ),
    url(    r'(?P<location>%s)/(?P<object_type>%s)/(?P<id>\d+)/delete/$' % (location_regexp, object_type_regexp),
            'object_delete',
            name = 'buildings_object_delete'
    ),
)

search_patterns = patterns('buildings.views',
    url(    r'search/$',
            'object_search',
            name = 'buildings_object_search'
    ),
    url(    r'search/(?P<location>%s)/(?P<object_type>%s)/$' % (location_regexp, object_type_regexp),
            'object_search',
            name = 'buildings_object_search'
    ),
)

urlpatterns = common_patterns + object_patterns + search_patterns

urls.py
# -*- coding:utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^realtors/', include('realtors.foo.urls')),
    (r'^$', include('welcome.urls')),
    
    (r'^accounts/', include('accounts.urls')),
    (r'^buildings/', include('buildings.urls')),
    
    (r'^images/', include('images.urls')),
    (r'^messages/', include('usermessages.urls')),
    # Django comments system
    (r'^comments/', include('django.contrib.comments.urls')),
    
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)

# ¡¡¡ Only in dev mode !!!
if settings.SERVE_STATIC:
    urlpatterns += patterns('django.contrib.staticfiles.views',
        url(r'^static/(?P<path>.*)$', 'serve'),
    )
    
    media_url = settings.MEDIA_URL
    if media_url[0] == '/':
        media_url = media_url[1:]
    urlpatterns += patterns('',
        (r'^%(media_url)s(?P<path>.*)$' % {'media_url': media_url},
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

buildings/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericRelation

from currencies.models import Currency

class Metro(models.Model):
    town = models.CharField(max_length = 100, db_index=True, verbose_name=u"Город")
    title = models.CharField(max_length = 100, db_index=True, verbose_name=u"Название станции")
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ['id']
        verbose_name = u"Метро"
        verbose_name_plural = u"Станции метро"
    

class ExtraParameters(models.Model):
    title = models.CharField(max_length=100, verbose_name=u"Название параметра")
    image = models.ImageField(upload_to='param_pictures', null=True, blank=True, verbose_name=u"Пиктограмма")
    
    content_types = models.ManyToManyField(ContentType, limit_choices_to = {'model__in': ['rentflat', 'sellflat']}, verbose_name=u"Модели")
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        verbose_name = u"Дополнительный параметр"
        verbose_name_plural = u"Дополнительные параметры"
    

# ============
# = Building =
# ============

# Managers
class SearchableManager(models.Manager):
    def get_query_set(self):
        return super(SearchableManager, self).get_query_set().filter(price_EUR__isnull = False)
    

class LocationManager(SearchableManager):
    def __init__(self, location, *args, **kwargs):
        super(LocationManager, self).__init__(*args, **kwargs)
        self.location = location
    
    def get_query_set(self):
        return super(LocationManager, self).get_query_set().filter(location = self.location)
    

class NotSearchableManager(models.Manager):
    def get_query_set(self):
        return super(NotSearchableManager, self).get_query_set().filter(price_EUR__isnull = True)
    


# Model
class Building(models.Model):
    LOCATION_CHOICES = (
        ('moscow', u'Москва'),
        ('moscow_region', u'Область'),
        ('common', u'Другой регион'),
    )
    
    owner = models.ForeignKey(User, verbose_name=u"Владелец")
    town = models.CharField(max_length = 100, db_index=True, verbose_name=u"Город")
    location = models.CharField(max_length = 50, choices=LOCATION_CHOICES, null=False, blank=False, db_index=True, verbose_name=u"Местоположение", help_text=u"используется для url и для выбора html-формы")
    street = models.CharField(max_length = 100, verbose_name=u"Улица")
    house_id = models.CharField(max_length = 10, verbose_name=u"Номер дома")
    building_id = models.CharField(max_length = 10, null=True, blank=True, verbose_name=u"Строение")
    
    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True, editable=False)
    lng = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True, editable=False)
    
    total_area = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True, verbose_name=u"Общая площадь", help_text=u"площадь в м\u00B2")
    
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name=u"Цена")
    currency = models.ForeignKey(Currency, verbose_name=u"Валюта")
    
    price_EUR = models.PositiveIntegerField(null=True, blank=True, db_index=True, editable=False)
    
    metro_remoteness_by_legs = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=u"до метро пешком", help_text=u"время в минутах")
    metro_remoteness_by_bus = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=u"до метро транспортом", help_text=u"время в минутах")
    mkad_remoteness = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name=u"от МКАД", help_text=u"расстояние в километрах")
    nearest_metro_stations = models.ManyToManyField(Metro, null=True, blank=True, verbose_name=u"Ближайшие станции метро")
    
    description = models.TextField(null=True, blank=True, verbose_name=u"Дополнительно")
    
    images = GenericRelation('images.ImagedItem')
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    deleted_at = models.DateTimeField(null=True, blank=True, editable=False)
    
    FIELDS_ALLOWED_TO_SORT = {
        'total_area': 'total_area',
        '-total_area': '-total_area',
    }
    
    def __unicode__(self):
        return u"Объект"
    
    def save(self, *args, **kwargs):
        char_id = self.currency.char_id
        try:
            self.price_EUR = int(self.price / self.currency.rate)
            if 'payment_period' in self._meta.get_all_field_names():
                self.price_EUR /= self.payment_period
        except Exception, e:
            raise e
        super(Building, self).save(*args, **kwargs)
    
    
    # ============
    # = Managers =
    # ============
    objects = models.Manager()
    moscow_objects = LocationManager(location='moscow')
    moscow_region_objects = LocationManager(location='moscow_region')
    common_objects = LocationManager(location = 'common')
    
    not_searchable = NotSearchableManager()
    
    class Meta:
        abstract = True
    
    @property
    def get_address(self):
        address = filter(None, [self.street, self.house_id, self.building_id])
        return ", ".join(address)
    
    def can_edit(self, user):
        return self.owner == user
    

# =========
# = Flats =
# =========
class HouseType(models.Model):
    title = models.CharField(max_length = 50, verbose_name=u"Тип дома")
    
    def __unicode__(self):
        return self.title

class RenovationType(models.Model):
    title = models.CharField(max_length = 50, verbose_name=u"Тип ремонта")
    
    def __unicode__(self):
        return self.title

class Flat(Building):
    __MAX_ROOMS_COUNT = 7
    ROOMS_COUNT_CHOICES = zip(
            xrange(1,__MAX_ROOMS_COUNT + 1), 
            map(str, xrange(1,__MAX_ROOMS_COUNT + 1))
        )
    
    BALCONY_COUNT_CHOICES = zip(xrange(6), map(str, xrange(6)))
    BATHROOM_COUNT_CHOICES = zip(xrange(4), map(str, xrange(4)))
    
    house_type = models.ForeignKey(HouseType, verbose_name=u"Тип дома")
    renovation_type = models.ForeignKey(RenovationType, verbose_name=u"Тип ремонта")
    is_new = models.BooleanField(default=False, verbose_name=u"Новостройка")
    
    # furniture = models.BooleanField(default=False, verbose_name=u"Мебель")
    # fridge = models.BooleanField(default=False, verbose_name=u"Холодильник")
    # wash_machine = models.BooleanField(default=False, verbose_name=u"Стиральная машина")
    # separated_bathroom = models.BooleanField(default=False, verbose_name=u"Раздельный санузел")
    # parking = models.BooleanField(default=False, verbose_name=u"Парковка")
    
    floor = models.PositiveSmallIntegerField(verbose_name=u"Этаж")
    floors_count = models.PositiveSmallIntegerField(verbose_name=u"Всего этажей")
    rooms_count = models.PositiveSmallIntegerField(db_index=True, choices=ROOMS_COUNT_CHOICES, verbose_name=u"Кол-во комнат")
    
    balcony_count = models.PositiveSmallIntegerField(default=0, choices=BALCONY_COUNT_CHOICES, verbose_name=u"Кол-во балконов")
    bathrooms_count = models.PositiveSmallIntegerField(default=1, choices=BATHROOM_COUNT_CHOICES, verbose_name=u"Кол-во ванных")
    
    kitchen_area = models.DecimalField(max_digits=8, decimal_places=3, null=True, blank=True, verbose_name=u"Площадь кухни", help_text=u"площадь в м\u00B2")
    
    Building.FIELDS_ALLOWED_TO_SORT.update({
        'rooms_count': 'rooms_count',
        '-rooms_count': '-rooms_count',
    })
    
    class Meta:
        abstract = True
    
    def clean(self):
        from django.core.exceptions import ValidationError
        if self.floors_count and self.floor > self.floors_count:
            raise ValidationError(u"Этаж не может быть больше количества этажей")
        if self.total_area and self.kitchen_area > self.total_area:
            raise ValidationError(u"Площадь кухни не может превышать общую площадь")
    

class RentFlat(Flat):
    PAYMENT_PERIOD_CHOICES = (
        (31, u'месяц'),
        (1, u'день'),
    )
    payment_period = models.PositiveSmallIntegerField(choices=PAYMENT_PERIOD_CHOICES, verbose_name=u"Период оплаты")
    
    agent_commission = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name=u"Комиссия агента", help_text=u"размер в %")
    
    # pets = models.BooleanField(default=False, verbose_name=u"Можно с животными")
    # children = models.BooleanField(default=False, verbose_name=u"Можно с детьми")
    
    extra_parameters = models.ManyToManyField(ExtraParameters, limit_choices_to = {'content_types__model': 'rentflat'}, null=True, blank=True,  verbose_name=u"Дополнительные параметры")
    
    Flat.FIELDS_ALLOWED_TO_SORT.update({
        'commission': 'agent_commission',
        '-commission': '-agent_commission',
    })
    
    # def save(self, *args, **kwargs):
    #     self.price_EUR /= self.payment_period
    #     super(RentFlat, self).save(*args, **kwargs)
    
    class Meta(Flat.Meta):
        verbose_name = u"Квартира в аренду"
        verbose_name_plural = u"Квартиры в аренду"
    
    def get_absolute_url(self):
        return reverse('buildings_object_detail', args=[self.location, 'rentflat', self.pk])
    

class SellFlat(Flat):
    mortgage = models.BooleanField(default=False, verbose_name=u"Ипотека")
    
    extra_parameters = models.ManyToManyField(ExtraParameters, limit_choices_to = {'content_types__model': 'sellflat'}, null=True, blank=True, verbose_name=u"Дополнительные параметры")
    
    part_in_flat = models.BooleanField(default=False, verbose_name=u"Доля в квартире")
    
    class Meta(Flat.Meta):
        verbose_name = u"Квартира для продажи"
        verbose_name_plural = u"Квартиры для продажи"
    
    def get_absolute_url(self):

templates/buildings/detail/building_detail_base.html
{% extends "buildings/base.html" %}
{% load building_fields_render %}

{% block sub_header %}
	<h4>Квартира</h4>
{% endblock %}

{% block top_panel %}
	{% if show_object_controls %}
		<ul class="menu">
			<li><a href="{% url buildings_object_edit location object_type object.id %}">Редактировать</a></li>
			<li><a href="{% url buildings_object_delete location object_type object.id %}">Удалить</a></li>
		</ul>
	{% endif %}
{% endblock %}

{% block content %}
	<div class="span-8">
		<div class="section_title">Адрес</div>
		<ul class="address">
			{% render_field object.town "Город" %}
			{% render_field object.street "Улица" %}
			{% render_field object.house_id "Дом" %}
			{% render_field object.building_id "Строение" %}
		
			{% block address %}{% endblock %}
		</ul>
		
		<div class="section_title">Удаленность</div>
		<ul class="remoteness">
			{% block remoteness %}{% endblock %}
		</ul>
		
		{% if object.nearest_metro_stations.exists %}
			<div class="section_title">Ближайшие станции метро</div>
			<ul class="nearest_metro_stations">
				{% for station in object.nearest_metro_stations.all %}
					<li>{{ station.title }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		
		<div class="section_title">Тип здания</div>
		<ul class="building_type">
			{% block building_type %}{% endblock %}
		</ul>
		
		<div class="section_title">Цена</div>
		<ul class="price">
			{# {% render_field object.price "Цена" object.currency %} #}
			<li>
				Цена: {{ object.price|floatformat:2 }} {{ object.currency }}
				{% if other_prices %}
					<ul>
						{% for currency, price in other_prices %}
							<li>
								или {{ price|floatformat:2 }} {{ currency }}
							</li>
						{% endfor %}
					</ul>
				{% endif %}
			</li>
			{% block price %}{% endblock %}
		</ul>
	</div>
	
	<div class="span-8">
		<div class="section_title">Параметры</div>
		<ul class="parameters">
			{% render_field object.total_area "Общая площадь" "м<sup>2</sup>" %}
		
			{% block parameters %}{% endblock %}
		</ul>
		
		{% if object.extra_parameters.exists %}
			<div class="section_title">Дополнительные параметры</div>
			<ul class="extra_parameters">
				{% for parameter in object.extra_parameters.all %}
					<li>{{ parameter.title }}</li>
				{% endfor %}
			</ul>
		{% endif %}
		
		<div class="section_title">Сведения о продавце</div>
		<ul class="realtor">
			<li>
				Риэлтор:
				<span>
					<a href="{{ object.owner.get_profile.get_absolute_url }}">{{ object.owner.get_profile.get_name }}</a>
				</span>
			</li>
		</ul>
	</div>
	
	<div class="span-8 last">
    {# TODO: Тут будет карта #}
	</div>
	
	{% if object.description %}
		<div class="span-24 last">
			<div class="section_title">Дополнительно</div>
			<div class="description">
				{{ object.description }}
			</div>
		</div>
	{% endif %}
	
	{% if object.images %}
		{% block head %}
			<script type="text/javascript" src="{{ STATIC_URL }}galleria/src/galleria.js"></script>
			<script type="text/javascript" src="{{ STATIC_URL }}galleria/src/themes/classic/galleria.classic.js"></script>
		{% endblock %}
		
		{% with object.images.all as images %}
			{% if images %}
				<div class="span-24 last">
					<div class="section_title">Фотографии</div>
					<div id="gallery" class="images gallery">
						{% for image in object.images.all %}
							<a href="{{ image.image.url }}"><img src="{{ image.thumbnail.url }}" title="{{ image.title }}"/></a>
						{% endfor %}
					</div>
				</div>
				<script type="text/javascript">
					$("#gallery").galleria({
						preload: 3,
				
						show_info: true,
						show_counter: false,
				
						min_scale_ratio: 1,
						max_scale_ratio: 1,
				
					});
				</script>
			{% endif %}
		{% endwith %}
	{% endif %}
{% endblock %}

templates/buildings/detail/common_rentflat_detail.html
{% extends "buildings/detail/rentflat_detail_base.html" %}

templates/buildings/detail/common_sellflat_detail.html
{% extends "buildings/detail/sellflat_detail_base.html" %}

templates/buildings/detail/flat_detail_base.html
{% extends "buildings/detail/building_detail_base.html" %}
{% load building_fields_render %}

{% block parameters %}
	{% render_field object.kitchen_area "Площадь кухни" "м<sup>2</sup>" %}
	{% render_field object.rooms_count "Кол-во комнат" %}
	{% render_field object.floor "Этаж" %}
	{% render_field object.floors_count "Всего этажей" %}
{% endblock %}

{% block building_type %}
	{% render_field object.house_type "Тип дома" %}
	{% render_field object.renovation_type "Тип ремонта" %}
	{% flag_field object.is_new "Новостройка" %}
{% endblock %}

{# {% block additional_parameters %} #}
{# 	{% render_field object.balcony_count "Кол-во балконов" %} #}
{# 	{% render_field object.bathrooms_count "Кол-во ванных" %} #}
{# 	{% flag_field object.furniture "Мебель" %} #}
{# 	{% flag_field object.fridge "Холодильник" %} #}
{# 	{% flag_field object.wash_machine "Стиральная машина" %} #}
{# 	{% flag_field object.separated_bathroom "Раздельный санузел" %} #}
{# 	{% flag_field object.parking "Парковка" %} #}
{# 	 #}
{# 	{% block flat_additional_parameters %}{% endblock %} #}
{# {% endblock %} #}

templates/buildings/detail/moscow_region_rentflat_detail.html
{% extends "buildings/detail/rentflat_detail_base.html" %}
{% load building_fields_render %}

{% block remoteness %}
	{% render_field object.mkad_remoteness "от МКАД" "км" %}
{% endblock %}

templates/buildings/detail/moscow_region_sellflat_detail.html
{% extends "buildings/detail/sellflat_detail_base.html" %}
{% load building_fields_render %}

{% block remoteness %}
	{% render_field object.mkad_remoteness "от МКАД" "км" %}
{% endblock %}

templates/buildings/detail/moscow_rentflat_detail.html
{% extends "buildings/detail/rentflat_detail_base.html" %}
{% load building_fields_render %}

{% block remoteness %}
	{% render_field object.metro_remoteness_by_legs "До метро пешком" "мин." %}
	{% render_field object.metro_remoteness_by_bus "До метро транспортом" "мин." %}
{% endblock %}

templates/buildings/detail/moscow_sellflat_detail.html
{% extends "buildings/detail/sellflat_detail_base.html" %}
{% load building_fields_render %}

{% block remoteness %}
	{% render_field object.metro_remoteness_by_legs "До метро пешком" "мин." %}
	{% render_field object.metro_remoteness_by_bus "До метро транспортом" "мин." %}
{% endblock %}

templates/buildings/detail/rentflat_detail_base.html
{% extends "buildings/detail/flat_detail_base.html" %}
{% load building_fields_render %}

{% block price %}
	{% render_field object.get_payment_period_display "Период оплаты" %}
	{% render_field object.agent_commission "Комиссия агента" %}
{% endblock %}

{# {% block flat_additional_parameters %} #}
{# 	{% flag_field object.pets "Можно с животными" %} #}
{# 	{% flag_field object.children "Можно с детьми" %} #}
{# {% endblock %} #}

templates/buildings/detail/sellflat_detail_base.html
{% extends "buildings/detail/flat_detail_base.html" %}
{% load building_fields_render %}

{% block price %}
	{% flag_field object.mortgage "Ипотека" %}
	{% flag_field object.part_in_flat "Доля в квартире" %}
{% endblock %}